### ISSUE TITLE
TODO-2016

### ISSUE THREAD

**Issue by mozillazg** [mozillazg/mozillazg.com#1]
## python
- [x] [如何从标准输入读取数据（让 CLI 程序支持管道和重定向输入）](https://mozillazg.com/2016/03/python-let-cli-support-pipe-read-data-from-stdin.html)
- [x] [让我们一起来构建一个模板引擎（－）](https://mozillazg.com/2016/03/let-us-build-a-template-engine-part1.html)
- [x] [让我们一起来构建一个模板引擎（三）](https://mozillazg.com/2016/03/let-us-build-a-template-engine-part3.html)
- [x] [让我们一起来构建一个模板引擎（二）](https://mozillazg.com/2016/03/let-us-build-a-template-engine-part2.html)
- [x] [让我们一起来构建一个模板引擎（四）](https://mozillazg.com/2016/06/let-us-build-a-template-engine-part4.html)
- [ ] 描述符简介
- [ ] 元类简介
- [ ] 让我们一起来构建一个 ORM（一）
- [ ] 让我们一起来构建一个 ORM（二）
- [ ] 让我们一起来构建一个 ORM（三）
- [ ] 让我们一起来构建一个 WEB 框架（一）
- [ ] 让我们一起来构建一个 WEB 框架（二）
- [ ] 让我们一起来构建一个 WEB 框架（三）
- [x] [Python 探针的奥秘](https://mozillazg.com/2016/04/apm-python-agent-principle.html)
- [ ] 使用 boost.python 封装 c/c++ 代码供 python 调用
- [ ] 使用 pybind11 封装 c/c++ 代码供 python 调用
- [ ] bottle 源码解析
- [x] [服务端模板攻击介绍 / 使用 exec 时需要注意的一些安全问题](https://mozillazg.com/2016/05/python-some-security-problems-about-use-exec-function.rst.html)
- [ ] go_coverage: 在本地查看测试覆盖率报告
- [ ] 让我们一起来构建一个 RPC 框架
  - [ ] 实现一个 RPC 框架
  - [ ] blog
- [ ] nsq  分布式消息队列服务
-  [ ] rabbitmq vs nsq vs kafka
- [ ] 异步 web 框架 aiohttp 快速入门教程
- [ ] 异步 http 请求库 aiohttp 使用简介
- [ ] 自定义异常类的正确姿势
- [x] [捕获异常然后再 raise 另一个异常的正确姿势](https://mozillazg.com/2016/08/python-the-right-way-to-catch-exception-then-reraise-another-exception.html)
-  [x] <del>写一个装饰器函数的正确姿势 </del>
- [ ] 让我们一起来构建一个模板引擎（续）（使用词法/语法分析的方式解析模板）
- [ ] 让我们一起来实现一个任务队列
- [x] [multiprocess + thread + logging = deadlock?](https://mozillazg.com/2016/09/python-threading-multiprocessing-logging-equal-deadlock.html)
- [ ] debug go program: bugsnag vs sentry
- [x] [python: 多继承模式下的 super 是如何工作的](https://mozillazg.com/2016/12/python-super-is-not-as-simple-as-you-thought.html)
## project
- [x] [go-unidecode](https://github.com/mozillazg/go-unidecode)
- [x] [go-slugify](https://github.com/mozillazg/go-slugify)
- [ ] go port of httpie
- [x] <del>给新版 docker registry 增加 qiniu storage driver(API 不支持获取断点续传的信息，无法支持镜像的断点续传，放弃)</del>
## 算法题
- [ ] 台阶问题
- [ ] 查找数组元素移动了多少位（有序数组，移动 n 位，针对移动后的数组，求 n 的值）
  
- [ ] 合并两个有序列表
- [ ] 排序，查找算法
- [ ] 子数组问题
