### ISSUE TITLE
TODO-2017

### ISSUE THREAD

**Issue by mozillazg** [mozillazg/mozillazg.com#2]
2017:

## 博客

* [x] [实现 Ruby 风格的字符串插值功能](https://mozillazg.github.io/2017/02/f-Implement-Ruby-Style-String-Interpolation.html)
* [ ] Golang 探针实现原理
      * [ ] http client 
      * [ ] http server
      * [ ] sql
      * [ ] ...
* [x] [使用 gdb 调试运行中的 python 进程](https://mozillazg.github.io/2017/07/debug-running-python-process-with-gdb.html)
* [ ] 让我们一起来实现一个任务队列
* [ ] 让我们一起来实现一个 web 框架
* [ ] 让我们一起来实现一个 ORM
* [x] [介绍 https://github.com/mozillazg/go-httpheader](https://mozillazg.github.io/2017/07/go-intro-go-httpheader.html)
* [ ] 元类

## 项目

* [ ] 更新 https://github.com/mozillazg/rust-pinyin
* [x] [实现 Ruby 风格的字符串插值功能](https://github.com/mozillazg/f)
* [x] [实现一个简单 job 队列框架（精简版的 rq/celery）](https://github.com/mozillazg/tinyq)
* [x] [go-cos](https://github.com/mozillazg/go-cos)
* [ ] coscli
* [ ] python-tips
* [ ] linux-tips
* [ ] go-tips
* [ ] ioloop

maybe 完成 [TODO-2016](https://github.com/mozillazg/blog/issues/1) 中一些（非全部）未完成的内容
